services:


  # ------------------------------------------
  # Jaeger
  # ------------------------------------------

  jaeger:

    image: cr.jaegertracing.io/jaegertracing/jaeger:2.20.0

    container_name: cosmos-learning-jaeger

    ports:

      - "16686:16686"


  # ------------------------------------------
  # OpenTelemetry Collector
  # ------------------------------------------

  otel-collector:

    image: otel/opentelemetry-collector:0.160.0

    container_name: cosmos-learning-otel-collector

    command:

      - "--config=/etc/otelcol/config.yaml"


    volumes:

      - ./otel-collector-config.yaml:/etc/otelcol/config.yaml


    ports:

      # OTLP gRPC

      - "4317:4317"


      # OTLP HTTP

      - "4318:4318"


      # Prometheus Metrics Exporter

      - "8889:8889"


    depends_on:

      - jaeger


  # ------------------------------------------
  # Prometheus
  # ------------------------------------------

  prometheus:

    image: prom/prometheus:latest

    container_name: cosmos-learning-prometheus


    ports:

      - "9090:9090"


    volumes:

      - ./prometheus.yml:/etc/prometheus/prometheus.yml


    depends_on:

      - otel-collector