using Microsoft.AspNetCore.Mvc;

namespace CosmosLearning.Api.Controllers;

[ApiController]
[Route("global-exception-demo")]
public sealed class GlobalExceptionDemoController : ControllerBase
{
    private readonly ILogger<GlobalExceptionDemoController> _logger;

    public GlobalExceptionDemoController(
        ILogger<GlobalExceptionDemoController> logger)
    {
        _logger = logger;
    }

    /// <summary>
    /// Demonstrates an unexpected unhandled exception.
    /// The Global Exception Handler should convert it into ProblemDetails.
    /// </summary>
    [HttpGet("unhandled")]
    public IActionResult ThrowUnhandledException()
    {
        _logger.LogInformation(
            "Demonstration endpoint: throwing an unhandled exception.");

        throw new Exception(
            "This is a deliberately generated exception for testing global exception handling.");
    }

    /// <summary>
    /// Demonstrates InvalidOperationException.
    /// </summary>
    [HttpGet("invalid-operation")]
    public IActionResult ThrowInvalidOperationException()
    {
        _logger.LogInformation(
            "Demonstration endpoint: throwing InvalidOperationException.");

        throw new InvalidOperationException(
            "The requested operation is not valid in the current state.");
    }

    /// <summary>
    /// Demonstrates ArgumentException.
    /// </summary>
    [HttpGet("invalid-argument")]
    public IActionResult ThrowArgumentException()
    {
        _logger.LogInformation(
            "Demonstration endpoint: throwing ArgumentException.");

        throw new ArgumentException(
            "The supplied argument is invalid.",
            "demoValue");
    }

    /// <summary>
    /// Demonstrates nested exceptions.
    /// </summary>
    [HttpGet("nested")]
    public IActionResult ThrowNestedException()
    {
        try
        {
            throw new InvalidOperationException(
                "The original inner exception.");
        }
        catch (Exception exception)
        {
            throw new Exception(
                "The outer exception was generated by the demo endpoint.",
                exception);
        }
    }

    /// <summary>
    /// Demonstrates asynchronous exceptions.
    /// </summary>
    [HttpGet("async")]
    public async Task<IActionResult> ThrowAsyncException()
    {
        _logger.LogInformation(
            "Async exception demonstration started. TraceId: {TraceId}",
            HttpContext.TraceIdentifier);

        await Task.Delay(100);

        _logger.LogInformation(
            "Async exception demonstration is about to throw. TraceId: {TraceId}",
            HttpContext.TraceIdentifier);

        throw new InvalidOperationException(
            "This exception occurred after an asynchronous operation.");
    }

    /// <summary>
    /// Demonstrates a successful request.
    /// Useful for comparing normal and exceptional behavior.
    /// </summary>
    [HttpGet("success")]
    public IActionResult Success()
    {
        _logger.LogInformation(
            "Demonstration endpoint completed successfully.");

        return Ok(new
        {
            message = "The request completed successfully.",
            correlationId = HttpContext.TraceIdentifier
        });
    }
}